#!/bin/sh

utddir=${UTDTOOLS}

if [ ! "${utddir}" ] ; then
  echo " "
  echo "ERROR[autotest]:UTDTOOLS is not set."
  echo "Please set UTDTOOLS to the utdtools root directory."
  echo " "
  exit 1
fi

version=${UTDTOOLSVERSION}
if [ ! "${version}" ] ; then
  echo " "
  echo "ERROR[autotest]:UTDTOOLSVERSION is not set."
  echo " "
  exit 1
fi

rdir=${utddir}/${version}
autodir=${rdir}/tcl/autotest
debug=
if [ $debug ] ; then
  echo "debug mode on"
  autodir=${utddir}/src/tcl/autotest
fi

if [ $# -lt 1 ] ; then
    exec ${rdir}/bin/utdos cometTix -n -do ${autodir}/autotest.tcl -s -- help
fi

exec ${rdir}/bin/utdos cometTix -p -n -do ${autodir}/autotest.tcl -s -- -libpath ${autodir} ${1+"$@"}

