#!/bin/sh

# Usage:
#       reg_programming
#       reg_programming low_res

utdtools=${UTDTOOLS}
if [ ! "${utdtools}" ] ; then
  echo "ERROR: UTDTOOLS environment variable not set." 
  echo "Please set it to the UTDTOOLS root directory using either"
  echo "source setenv.sh"
  echo "or"
  echo "source setenv.csh"
  echo "depending on your shell."
  exit 1;
fi

export DYLD_LIBRARY_PATH="${UTDTOOLS}/${UTDTOOLSVERSION}/lib/${UTDTOOLSOS}"
DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}" cometTix -do ${utdtools}/${UTDTOOLSVERSION}/tcl/reg_programming/reg_programming.tcl -- libpath ${utdtools}/${UTDTOOLSVERSION}/tcl/reg_programming $1
