/* ----------------------------------------------------------------- 
FILE:	    tknew.h                                       
DESCRIPTION:New functions added to tk for TimberWolf to work.
CONTENTS:   
DATE:	    Fri Oct 21 21:32:16 CDT 1994
REVISIONS:  
 * $Log: tknew.h,v $
 * Revision 1.1  2023/10/08 14:08:19  billswartz7
 * Initial revision
 *
 * Revision 1.1  2023/03/15 15:02:05  billswartz7
 * Initial revision
 *
 * Revision 1.11  2018/11/12 04:16:47  bills
 * Updated to handle RCS fiasco.
 *
 * Revision 1.11  2016/05/25 15:03:18  bills
 * Added missing TkinstallUserExit prototype.
 *
 * Revision 1.10  2004/03/05 18:26:00  bills
 * Now longer need Tk_CanvasWidgetCmd because these are autogenerated.
 * 
 * Revision 1.9  2002/01/04  00:20:31  bills
 * Added Tk_CanvasScrollbarFunc to support canvas scrollbars.
 *
 * Revision 1.8  2000/05/29  03:56:18  bills
 * Added Tk_CanvasWidgetCmd and now return the current canvas in routine
 * Tk_CanvasDispFunc.
 *
 * Revision 1.7  1997/05/10  15:42:47  bills
 * Added TkDeleteXEventSource.
 *
 * Revision 1.6  1997/02/07  18:09:47  bills
 * Added TkInstallXtEventSource TkXtEventSource TkRestoreXEventSource
 * for the netscape plugin.
 *
 * Revision 1.5  1997/01/21  06:31:19  bills
 * Added the Tk_WindowCreationHandler and Tk_Window_DeletionHandler routines.
 *
 * Revision 1.4  1997/01/16  21:35:17  bills
 * Added Tk_ParasiteDisplay.  Now Tk can use a parasite display.
 *
 * Revision 1.3  1995/08/26  17:12:05  bills
 * Added missing Button prototypes.h
 *
 * Revision 1.2  1994/11/06  09:06:06  bills
 * Make Tk_CanvasDispFunc arguments consistent.
 *
 * Revision 1.1  1994/10/27  18:20:37  bills
 * Initial revision
 *
----------------------------------------------------------------- */
#ifndef _TKNEW_H
#define _TKNEW_H

/* New routines added by ME */
EXTERN void TkWmParasite(Tk_Window winPtr) ;
EXTERN void Tk_ParasiteWindow(Window parasite) ;
EXTERN void Tk_ParasiteDisplay(Display *display) ;
EXTERN void Tk_ParasiteRestore(Tk_Window tkwin) ;
EXTERN Tk_Window *Tk_WindowChildren(Tk_Window tkwin, int *num_children) ;
EXTERN void Tk_UnmapParasite(Tk_Window tkwin) ;
EXTERN void *Tk_CanvasDispFunc( void (*func)(void *) ) ;
EXTERN void *Tk_CanvasScrollbarFunc(void (*sbar_func)(struct TkCanvas *canvas)) ;
EXTERN void Tk_CanvasDispUpdate( void ) ;
EXTERN void Tk_DisplayButton(ClientData clientData) ;
EXTERN void Tk_DisplayButtonText(ClientData clientData,char *text) ;
EXTERN void Tk_WindowCreationHandler(void (*proc)(Display *disp, Window win) ) ;
EXTERN void Tk_WindowDeletionHandler(void (*proc)(Display *disp, Window win) ) ;
EXTERN void TkInstallXtEventSource(void) ;
EXTERN void TkDeleteXEventSource(void) ;
EXTERN void TkXtEventSource(void) ;
EXTERN void TkRestoreXEventSource(void) ;
EXTERN void TkinstallUserExit( void (*user_routine)(void) ) ;

#endif /* _TKNEW_H */
