#include <cometconfig.h>
#include <utd/base.h>
#include <utd/string.h>
#include <utd/msg.h>
#include <tcl/tcl.h>

int EZeval_html_library(Tcl_Interp *interp) 
{
 int size = 1627;
 int i,err,length;
 char *script ;
 const char *trace;
 char *cmds[] = {
   "",
   "namespace eval twez {",
   "",
   "  variable urlS",
   "  variable stopS",
   "  variable hwinS",
   "  variable FontS",
   "  variable eventS",
   "  variable loadedS",
   "  variable events2S",
   "  variable esc_mapS",
   "  variable tag_mapS ",
   "  variable form_mapS ",
   "  variable insert_mapS ",
   "  variable list_elementS ",
   "  variable text_mapS",
   "  variable table_colS",
   "  variable table_rowS",
   "  variable alphanumericS a-zA-Z0-9",
   "  variable table_alignS",
   "  variable html_param_mapS",
   "",
   "  array set tag_mapS {",
   "	  b      {weight bold}",
   "	  blockquote	{style i indent 1 Trindent rindent}",
   "	  bq		{style i indent 1 Trindent rindent}",
   "	  cite   {style i}",
   "	  code   {family courier}",
   "	  dfn    {style i}	",
   "	  dir    {indent 1}",
   "	  dl     {indent 1}",
   "	  em     {style i}",
   "	  h1     {size 24 weight bold}",
   "	  h2     {size 22}		",
   "	  h3     {size 20}	",
   "	  h4     {size 18}",
   "	  h5     {size 16}",
   "	  h6     {style i}",
   "	  i      {style i}",
   "	  kbd    {family courier weight bold}",
   "	  menu     {indent 1}",
   "	  ol     {indent 1}",
   "	  pre    {fill 0 family courier Tnowrap nowrap}",
   "	  samp   {family courier}		",
   "	  strong {weight bold}		",
   "	  tt     {family courier}",
   "	  u	 {Tunderline underline}",
   "	  ul     {indent 1}",
   "	  var    {style i}	",
   "  }",
   "",
   "",
   "  array set tag_mapS {",
   "	  center {Tcenter center}",
   "	  strike {Tstrike strike}",
   "	  u	 {Tunderline underline}",
   "  }",
   "",
   "",
   "  set tag_mapS(hmstart) {",
   "	family times   weight medium   style r   size 14",
   "	Tcenter \"\"   Tlink \"\"   Tnowrap \"\"   Tunderline \"\"   list list",
   "	fill 1   indent \"\" counter 0 adjust 0",
   "  }",
   "",
   "  array set tag_mapS {",
   "	  family {times}",
   "	  weight {medium}",
   "	  style  {r}",
   "	  size  {14}",
   "  }",
   "",
   "",
   "  array set insert_mapS {",
   "	  blockquote \"\\n\" /blockquote \"\"",
   "	  br	\"\"",
   "	  dd	\"\" /dd	\"\"",
   "	  dl	\"\" /dl	\"\"",
   "	  dt	\"\\n\"",
   "	  form \"\"	/form \"\"",
   "	  h1	\"\\n\"	/h1	\"\"",
   "	  h2	\"\\n\"	/h2	\"\"",
   "	  h3	\"\\n\"	/h3	\"\"",
   "	  h4	\"\"	/h4	\"\"",
   "	  h5	\"\"	/h5	\"\"",
   "	  h6	\"\"	/h6	\"\"",
   "	  li   \"\"",
   "	  /dir \"\"",
   "	  /ul \"\"",
   "	  /ol \"\"",
   "	  /menu \"\"",
   "	  p	\"\\n\"",
   "	  pre \"\"	/pre \"\"",
   "  }",
   "",
   "",
   "  array set zap_text_mapS {",
   "	  title 1",
   "	  script    1",
   "  }",
   "",
   "",
   "  array set list_elementS {",
   "	  ol 1   ul 1   menu 1   dl 1   dir 1",
   "  }",
   "",
   "  proc init_win {win} {",
   "	  upvar #0 HM$win var",
   "	  ",
   "	  init_state $win",
   "	  $win tag configure underline -underline 1",
   "	  $win tag configure center -justify center",
   "	  $win tag configure nowrap -wrap none",
   "	  $win tag configure rindent -rmargin $var(S_tab)c",
   "	  $win tag configure strike -overstrike 1",
   "	  $win tag configure mark -foreground red	;# list markers",
   "	  $win tag configure list -spacing1 3p -spacing3 3p ;# regular lists",
   "	  $win tag configure compact -spacing1 0p	;# compact lists",
   "	  $win tag configure link -borderwidth 2 -foreground blue -underline true",
   "	  set_indent $win $var(S_tab)",
   "	  $win configure -wrap word",
   "",
   "	  $win mark set $var(S_insert) 1.0",
   "",
   "	  $win tag configure thin -font [x_font times 4 medium r]",
   "	  $win tag configure hr -relief sunken -borderwidth 2 -wrap none \\",
   "		  -tabs [winfo width $win]",
   "	  bind $win <Configure> {",
   "		  %W tag configure hr -tabs %w",
   "		  %W tag configure last -spacing3 %h",
   "	  }",
   "",
   "",
   "	  $win tag bind link <1> \"::twez::link_hit $win %x %y\"",
   "  }",
   "",
   "",
   "  proc set_indent {win cm} {",
   "	  set tabs [expr {$cm / 2.0}]",
   "	  $win configure -tabs ${tabs}c",
   "	  foreach i {1 2 3 4 5 6 7 8 9} {",
   "		  set tab [expr {$i * $cm}]",
   "		  $win tag configure indent$i -lmargin1 ${tab}c -lmargin2 ${tab}c \\",
   "			  -tabs \"[expr {$tab + $tabs}]c [expr {$tab + 2*$tabs}]c\"",
   "	  }",
   "  }",
   "",
   "",
   "  proc reset_win {win} {",
   "	  upvar #0 HM$win var",
   "	  regsub -all { +[^L ][^ ]*} \" [$win tag names] \" {} tags",
   "	  catch \"$win tag delete $tags\"",
   "	  eval $win mark unset [$win mark names]",
   "	  $win delete 0.0 end",
   "	  $win tag configure hr -tabs [winfo width $win]",
   "",
   "	  $win mark set $var(S_insert) 1.0",
   "",
   "	  catch {unset [info globals HM$win.form*]}",
   "",
   "	  init_state $win",
   "	  return HM$win",
   "  }",
   "",
   "",
   "  proc init_state {win} {",
   "	  upvar #0 HM$win var",
   "	  variable stopS",
   "	  set stopS 0",
   "	  array set tmp [array get var S_*]",
   "	  if {[info exists var]} {",
   "	    catch {unset var}",
   "	  }",
   "	  array set var {",
   "		  stop 0",
   "		  xmp 0",
   "		  tags 0",
   "		  xmp_tags {}",
   "		  fill 0",
   "		  list list",
   "		  S_adjust_size 0",
   "		  S_tab 1.0",
   "		  S_unknown \\xb7",
   "		  S_update 10",
   "		  S_symbols O*=+-o\\xd7\\xb0>:\\xb7",
   "		  S_insert Insert",
   "		  S_home file",
   "		  S_cwd cwd",
   "		  S_ignore 0",
   "		  curtable {}",
   "		  divert 0",
   "		  divert_win {}",
   "		  S_restore_win {}",
   "		  S_back_proc {}",
   "		  S_file {}",
   "		  S_notebook {}",
   "		  S_page {}",
   "	  }",
   "	  array set var [array get tmp]",
   "  }",
   "",
   "  proc file_init {win} {",
   "	  upvar #0 HMfile$win var",
   "",
   "	  array set var {}",
   "  }",
   "",
   "  proc file_stop {win file state} {",
   "	  upvar #0 HMfile$win var",
   "",
   "	  set var($file) $state",
   "  }",
   "",
   "  proc file_release {win} {",
   "	  upvar #0 HMfile$win var",
   "",
   "	  foreach a [array names var] {",
   "",
   "	    if {$var($a)} {",
   "	      return 0 ;",
   "	    }",
   "	  }",
   "	  return 1 ;",
   "  }",
   "",
   "",
   "  array set html_param_mapS {",
   "	  -update S_update",
   "	  -tab S_tab",
   "	  -unknown S_unknown",
   "	  -stop stop",
   "	  -size S_adjust_size",
   "	  -symbols S_symbols",
   "	  -insert S_insert",
   "	  -home S_home",
   "	  -cwd S_cwd",
   "	  -ignore S_ignore",
   "	  -divert divert",
   "	  -divert_win divert_win",
   "	  -curtable curtable",
   "	  -restore_win S_restore_win",
   "	  -back_callback S_back_proc",
   "	  -file S_file",
   "	  -page S_page",
   "	  -notebook S_notebook",
   "  }",
   "",
   "  proc set_state {win args} {",
   "	  upvar #0 HM$win var",
   "	  variable html_param_mapS ",
   "	  set bad 0",
   "	  if {[catch {array set params $args}]} {",
   "	    return 0",
   "	  }",
   "	  foreach i [array names params] {",
   "		  incr bad [catch {set var($html_param_mapS($i)) $params($i)}]",
   "	  }",
   "	  return [expr {$bad == 0}]",
   "  }",
   "",
   "",
   "  ",
   "  proc render {win tag_orig not param text} {",
   "	  variable tag_mapS ",
   "	  variable insert_mapS",
   "	  variable zap_text_mapS",
   "	  variable list_elementS ",
   "",
   "	  upvar #0 HM$win var",
   "	  variable stopS",
   "	  if {$var(stop) || $stopS} {",
   "	    return",
   "	  }",
   "	  set tag [string tolower $tag_orig]",
   "	  if {$var(S_ignore)} {",
   "	    if {$tag == \"script\"} {",
   "		if {[catch {::twez::tag_$not$tag $win $param $text} msg]} {",
   "		  return ;",
   "		} else {",
   "		  if {$msg == 1} {",
   "		    return ;",
   "		  } else {",
   "		    set tag noop",
   "		  }",
   "		}",
   "	      } else {",
   "		return ;",
   "	      }",
   "	    }",
   "	    if {$var(xmp)} {",
   "	      if { !(($tag == \"xmp\") && ($not == \"/\")) } {",
   "		if {$not == \"/\"} {",
   "		  catch {$win insert $var(S_insert) \"</$tag_orig\" $var(xmp_tags)}",
   "		} else {",
   "		  catch {$win insert $var(S_insert) \"<$tag_orig\" $var(xmp_tags)}",
   "		}",
   "		if {$param != \"\"} {",
   "		  catch {$win insert $var(S_insert) \" $param\" $var(xmp_tags)}",
   "		}",
   "		catch {$win insert $var(S_insert) \">$text\" $var(xmp_tags)}",
   "		return ;",
   "	      }",
   "	    }",
   "	    set text [map_esc $text]",
   "",
   "	    if {[info exists list_elementS($tag)]} {",
   "		    set list \"list [expr {[extract_param $param compact] ? \"compact\" : \"list\"}]\"",
   "	    } else {",
   "		    set list \"\"",
   "	    }",
   "",
   "	    if {$tag == \"td\" } {",
   "	      catch {tag_$not$tag $win $param $text} msg",
   "	      return ;",
   "	    }",
   "	    if {($tag == \"cond\") && ($not != \"/\") && ($text != \"\") } {",
   "	      if {[catch {tag_$not$tag $win $param $text} msg]} {",
   "		puts stderr \"ERROR in logic...\"",
   "	      } else {",
   "		if {$msg == 1} {",
   "		  return ;",
   "		} else {",
   "		  set tag color",
   "		}",
   "	      }",
   "	    }",
   "",
   "",
   "	    if {$var(divert)} {",
   "	      set win $var(divert_win)",
   "	      upvar #0 HM$win var",
   "	    }",
   "",
   "	    catch {stack $win $not \"$tag_mapS($tag) $list\"}",
   "",
   "	    if {[info exists insert_mapS($not$tag)]} {",
   "	      if {[lindex [split [$win index $var(S_insert)] .] 1] != 0} {",
   "		 $win insert $var(S_insert) \\n \"space $var(font)\"",
   "	      }",
   "	      $win insert $var(S_insert) $insert_mapS($not$tag) \"space $var(font)\"",
   "",
   "	      if {[lindex $var(fill) end]} {",
   "		set text [string trimleft $text]",
   "	      }",
   "	    }",
   "",
   "	    if {[lindex $var(fill) end]} {",
   "		    set text [zap_white $text]",
   "	    } else {",
   "		    set text [translate_cr $text]",
   "	    }",
   "",
   "	    catch {mark $not$tag $win $param $text} err",
   "",
   "	    catch {tag_$not$tag $win $param $text} msg",
   "",
   "	    if {[info exists zap_text_mapS($not$tag)]} {",
   "	      if {!([incr var(tags)] % $var(S_update))} {",
   "		    update",
   "	      }",
   "	      return ;",
   "	    }",
   "",
   "	    set tags [current_tags $win]",
   "	    $win insert $var(S_insert) $text $tags",
   "",
   "	    if {!([incr var(tags)] % $var(S_update))} {",
   "		    update",
   "	    }",
   "    }",
   "",
   "",
   "",
   "    proc tag_hmstart {win param text} {",
   "	    upvar #0 HM$win var",
   "	    $win mark gravity $var(S_insert) left",
   "	    $win insert end \"\\n \" last",
   "	    $win mark gravity $var(S_insert) right",
   "    }",
   "",
   "    proc tag_/hmstart {win param text} {",
   "	    $win delete last.first end",
   "    }",
   "",
   "",
   "    proc tag_title {win param text} {",
   "	    upvar $text data",
   "	    wm title [winfo toplevel $win] $data",
   "	    set data \"\"",
   "    }",
   "",
   "    proc tag_hr {win param text} {",
   "	    upvar #0 HM$win var",
   "	    $win insert $var(S_insert) \"\\n\" space \"\\n\" thin \"\\t\" \"thin hr\" \"\\n\" thin",
   "    }",
   "",
   "",
   "    proc tag_ol {win param text} {",
   "	    upvar #0 HM$win var",
   "	    set var(count$var(level)) 0",
   "    }",
   "",
   "    proc tag_ul {win param text} {",
   "	    upvar #0 HM$win var",
   "	    catch {unset var(count$var(level))}",
   "    }",
   "",
   "    proc tag_menu {win param text} {",
   "	    upvar #0 HM$win var",
   "	    set var(menu) ->",
   "	    set var(compact) 1",
   "    }",
   "",
   "    proc tag_/menu {win param text} {",
   "	    upvar #0 HM$win var",
   "	    catch {unset var(menu)}",
   "	    catch {unset var(compact)}",
   "    }",
   "",
   "    proc tag_xmp {win param text} {",
   "	    upvar #0 HM$win var",
   "	    set var(xmp) 1",
   "	    stack $win \"\" \"fill 0 family courier Tnowrap nowrap\"",
   "	    set var(xmp_tags) [current_tags $win]",
   "    }",
   "",
   "    proc tag_/xmp {win param text} {",
   "	    upvar #0 HM$win var",
   "	    set var(xmp) 0",
   "	    stack $win / \"fill 0 family courier Tnowrap nowrap\"",
   "    }",
   "	    ",
   "    proc tag_dt {win param text} {",
   "	    upvar #0 HM$win var",
   "	    upvar $text data",
   "	    set level $var(level)",
   "	    incr level -1",
   "	    $win insert $var(S_insert) \"$data\" \\",
   "		    \"hi [lindex $var(list) end] indent$level $var(font)\"",
   "	    set data {}",
   "    }",
   "",
   "    proc tag_li {win param text} {",
   "	    upvar #0 HM$win var",
   "	    set level $var(level)",
   "	    incr level -1",
   "	    set x [string index $var(S_symbols)+-+-+-+-\" $level]",
   "	    catch {set x [incr var(count$level)]}",
   "	    catch {set x $var(menu)}",
   "	    $win insert $var(S_insert) \\t$x\\t \"mark [lindex $var(list) end] indent$level $var(font)\"",
   "    }",
   "",
   "",
   "    proc tag_a {win param text} {",
   "	    upvar #0 HM$win var",
   "",
   "",
   "	    if {[extract_param $param href]} {",
   "		    set var(Tref) [list L:$href]",
   "		    stack $win \"\" \"Tlink link\"",
   "		    link_setup $win $href",
   "	    }",
   "",
   "",
   "	    if {[extract_param $param name]} {",
   "		    set var(Tname) [list N:$name]",
   "		    stack $win \"\" \"Tanchor anchor\"",
   "		    $win mark set N:$name \"$var(S_insert) - 1 chars\"",
   "		    $win mark gravity N:$name left",
   "		    if {[info exists var(goto)] && $var(goto) == $name} {",
   "			    unset var(goto)",
   "			    set var(going) $name",
   "		    }",
   "	    }",
   "    }",
   "",
   "",
   "    proc goto {win where {callback went_to}} {",
   "	    upvar #0 HM$win var",
   "	    if {[regexp N:$where [$win mark names]]} {",
   "		    $win see N:$where",
   "		    update",
   "		    eval $callback $win [list $where]",
   "		    return 1",
   "	    } else {",
   "		    set var(goto) $where",
   "		    return 0",
   "	    }",
   "    }",
   "",
   "",
   "    proc went_to {win where {count 0} {color orange}} {",
   "	    upvar #0 HM$win var",
   "	    if {$count > 5} return",
   "	    set var(goto_enabled) 1",
   "	    catch {$win tag configure N:$where -foreground $color}",
   "	    update",
   "	    after 200 [list ::twez::went_to $win $where [incr count] \\",
   "				    [expr {$color==\"orange\" ? \"\" : \"orange\"}]]",
   "    }",
   "",
   "    proc tag_/a {win param text} {",
   "	    upvar #0 HM$win var",
   "	    if {[info exists var(Tref)]} {",
   "		    unset var(Tref)",
   "		    stack $win / \"Tlink link\"",
   "	    }",
   "",
   "",
   "	    if {[info exists var(going)]} {",
   "		    $win yview N:$var(going)",
   "		    update",
   "		    went_to $win $var(going)",
   "		    unset var(going)",
   "	    }",
   "",
   "	    if {[info exists var(Tname)]} {",
   "		    unset var(Tname)",
   "		    stack $win / \"Tanchor anchor\"",
   "	    }",
   "    }",
   "",
   "",
   "    proc tag_img {win param text} {",
   "	    upvar #0 HM$win var",
   "	    variable eventS",
   "",
   "	    array set align_map {",
   "	      top top",
   "	      texttop top",
   "	      middle center",
   "	      absmiddle center",
   "	      center center",
   "	      baseline bottom",
   "	      absbottom bottom",
   "	    }",
   "	    set align center ;# The spec isn't clear what the default should be",
   "	    set param [string tolower $param]",
   "	    if {[extract_param $param align]} {",
   "	      catch {set align $align_map([string tolower $align])}",
   "	    }",
   "",
   "	    set alt \"<image>\"",
   "	    extract_param $param alt",
   "	    set alt [map_esc $alt]",
   "",
   "	    set border 0",
   "	    extract_param $param border",
   "",
   "	    set item $win.$var(tags)",
   "	    if {[extract_param $param width] && [extract_param $param height]} {",
   "	      set e [expr {$var(divert)}]",
   "	      if {$e} {",
   "		set pwin [winfo parent $var(divert_win)]",
   "		set owidth [lindex [$pwin configure -width] 4]",
   "		set oheight [lindex [$pwin configure -height] 4]",
   "		$pwin configure -width $width",
   "		$pwin configure -height $height",
   "		set var(table_image) 1",
   "	      } else {",
   "	      }",
   "	      frame $item -width $width -height $height",
   "	      pack $item -expand 1 -fill both",
   "	      pack propagate $item 0",
   "	      set label $item.label",
   "	      label $label -width $width -height $height",
   "	      pack $label -expand 1 -fill both",
   "	    } else {",
   "	      set label $item",
   "	      label $label ",
   "	    }",
   "",
   "	    $label configure -relief ridge -fg orange -text $alt",
   "	    catch {$label configure -borderWidth $border}",
   "	    if {$border == 0} {",
   "	      set bgcolor [lindex [$win configure -background] 4]",
   "	      $item configure -borderwidth 0",
   "	      $label configure -background $bgcolor",
   "	    }",
   "	    if {[catch {$win window create $var(S_insert) -align $align -window $item -pady 2 -padx 2} emsg]} {",
   "	      puts stderr \"ERROR:$emsg $param\\n[stacktrace]\\n\"",
   "	    }",
   "",
   "	    set tags [current_tags $win]",
   "	    foreach tag $tags {",
   "		    $win tag add $tag $item",
   "	    }",
   "",
   "	    if {[extract_param $param ismap]} {",
   "		    set link [lindex $tags [lsearch -glob $tags L:*]]",
   "		    regsub L: $link {} link",
   "		    regsub -all {%} $link {%%} link2",
   "		    foreach i [array names eventS] {",
   "			    bind $label <$i> \"catch \\{%W configure $eventS($i)\\}\"",
   "		    }",
   "		    bind $label <1> \"+::twez::link_callback $win $link2?%x,%y\"",
   "	    } ",
   "",
   "	    set src \"\"",
   "	    extract_param $param src",
   "	    set_image $win $label $src",
   "	    return $label	;# used by the forms package for input_image types",
   "    }",
   "",
   "",
   "",
   "    proc got_image {win image_error} {",
   "	    if {[winfo name $win] == \"label\"} {",
   "		    pack propagate [winfo parent $win] 1",
   "	    }",
   "	    if {[catch {$win configure -image $image_error}]} {",
   "		    $win configure -image {}",
   "		    $win configure -text $image_error",
   "	    }",
   "    }",
   "",
   "",
   "    array set eventS {",
   "	  Enter	{-borderwidth 2 -relief raised }",
   "	  Leave	{-borderwidth 2 -relief flat }",
   "  }",
   "",
   "  proc message_clean {args} {",
   "    ez_message msg \"\"",
   "  }",
   "",
   "  array set events2S {",
   "	  Enter	{::twez::ez_message msg}",
   "	  Leave	{::twez::message_clean}",
   "  }",
   "",
   "",
   "  proc link_setup {win href} {",
   "	  variable eventS",
   "	  variable events2S",
   "	  regsub -all {%} $href {%%} href2",
   "	  foreach i [array names eventS] {",
   "	    eval {$win tag bind  L:$href <$i>} \\",
   "	      \\{$win tag configure \\{L:$href2\\} $eventS($i) \\; \\",
   "	      $events2S($i) $href \\}",
   "	  }",
   "  }",
   "",
   "",
   "  proc link_hit {win x y} {",
   "	  set tags [$win tag names @$x,$y]",
   "	  set link [lindex $tags [lsearch -glob $tags L:*]]",
   "	  regsub L: $link {} link",
   "	  link_callback $win $link",
   "  }",
   "",
   "",
   "",
   "",
   "  proc extract_param {param key {val \"\"}} {",
   "",
   "	  if {$val == \"\"} {",
   "		  upvar $key result",
   "	  } else {",
   "		  upvar $val result",
   "	  }",
   "      set ws \"    \\n\\r\"",
   "   ",
   "      if {",
   "	[regsub -nocase [format {.*%s[%s]*=[%s]*\"([^\"]*).*} $key $ws $ws] $param {\\1} value] ||",
   "	[regsub -nocase [format {.*%s[%s]*=[%s]*'([^']*).*} $key $ws $ws] $param {\\1} value] ||",
   "	[regsub -nocase [format {.*%s[%s]*=[%s]*([^%s]+).*} $key $ws $ws $ws] $param {\\1} value] } {",
   "	  set result $value",
   "	  return 1",
   "      }",
   "",
   "	  ",
   "	  set bad \\[^a-zA-Z\\]+",
   "	  if {[regexp -nocase  \"$bad$key$bad\" -$param-]} {",
   "		  return 1",
   "	  } else {",
   "		  return 0",
   "	  }",
   "  }",
   "",
   "",
   "",
   "  proc stack {win push list} {",
   "	  upvar #0 HM$win var",
   "	  array set tags $list",
   "	  if {$push == \"\"} {",
   "		  foreach tag [array names tags] {",
   "			  lappend var($tag) $tags($tag)",
   "		  }",
   "	  } else {",
   "		  foreach tag [array names tags] {",
   "			  set var($tag) [lreplace $var($tag) end end]",
   "		  }",
   "	  }",
   "  }",
   "",
   "",
   "  proc current_tags {win} {",
   "	  upvar #0 HM$win var",
   "	  set font font",
   "	  foreach i {family size weight style} {",
   "		  if {[catch {set $i [lindex $var($i) end]} msg]} {",
   "		    variable tag_mapS",
   "		    set $i $tag_mapS($i)",
   "		    icalert_user errmsg null \"Load failure. Please reload.\"",
   "		  }",
   "		  append font :[set $i]",
   "	  }",
   "	  set xfont [x_adjfont $family $size $weight $style $var(S_adjust_size)]",
   "	  set_font $win $font $xfont",
   "	  if {[catch {set indent [llength $var(indent)]} msg]} {",
   "	    set var(indent) 1",
   "	    set indent 1",
   "	  }",
   "	  incr indent -1",
   "	  lappend tags $font indent$indent",
   "	  foreach tag [array names var T*] {",
   "		  lappend tags [lindex $var($tag) end]	;# test",
   "	  }",
   "	  set var(font) $font",
   "	  set var(xfont) [$win tag cget $font -font]",
   "	  set var(level) $indent",
   "	  return $tags",
   "  }",
   "",
   "",
   "",
   "  proc x_font {family size weight style {adjust_size 0}} {",
   "	  catch {incr size $adjust_size}",
   "	  return \"-*-$family-$weight-$style-normal-*-*-${size}0-*-*-*-*-*-*\"",
   "  }",
   "",
   "  proc x_adjfont {family size weight style {adjust_size 0}} {",
   "    catch {incr size $adjust_size}",
   "    return [twhtml_xfont \"-*-$family-$weight-$style-normal-*-*-${size}0-*-*-*-*-*-*\"]",
   "  }",
   "",
   "",
   "",
   "  proc parse_html {html {cmd test_parse} {start hmstart}} {",
   "	  regsub -all \\{ $html {\\&ob;} html",
   "	  regsub -all \\} $html {\\&cb;} html",
   "	  set w \" \\t\\r\\n\"	;# white space",
   "	  proc cl x {return \"\\[$x\\]\"}",
   "	  set exp <(/?)([cl ^$w>]+)[cl $w]*([cl ^>]*)>",
   "	  set sub \"\\}\\n$cmd {\\\\2} {\\\\1} {\\\\3} \\{\"",
   "	  regsub -all $exp $html $sub html",
   "	  eval \"$cmd {$start} {} {} \\{ $html \\}\"",
   "	  eval \"$cmd {$start} / {} {}\"",
   "  }",
   "",
   "  proc test_parse {command tag slash text_after_tag} {",
   "	  puts \"==> $command $tag $slash $text_after_tag\"",
   "  }",
   "",
   "",
   "  proc zap_white {data} {",
   "	  regsub -all \"\\[ \\t\\r\\n\\]+\" $data \" \" data",
   "	  return $data",
   "  }",
   "",
   "  proc translate_cr {data} {",
   "      regsub -all \"\\r+\" $data \"\\n\" data",
   "      return $data",
   "  }",
   "",
   "",
   "  proc map_esc {text} {",
   "	  if {![regexp & $text]} {return $text}",
   "	  regsub -all {([][$\\\\])} $text {\\\\\\1} new",
   "	  regsub -all {&#([0-9][0-9]?[0-9]?);?} \\",
   "		  $new {[format %c [scan \\1 %d tmp;set tmp]]} new",
   "	  regsub -all {&([a-zA-Z]+);?} $new {[do_map \\1]} new",
   "	  return [subst $new]",
   "  }",
   "",
   "",
   "  proc do_map {text {unknown ?}} {",
   "	  variable esc_mapS",
   "	  set result $unknown",
   "	  catch {set result $esc_mapS($text)}",
   "	  return $result",
   "  }",
   "",
   "",
   "  array set esc_mapS {",
   "     lt <   gt >   amp &   quot \\\"   copy \\xa9",
   "     reg \\xae   ob \\x7b   cb \\x7d   nbsp \\xa0",
   "  }",
   "",
   "  array set esc_mapS {",
   "	  nbsp \\xa0 iexcl \\xa1 cent \\xa2 pound \\xa3 curren \\xa4",
   "	  yen \\xa5 brvbar \\xa6 sect \\xa7 uml \\xa8 copy \\xa9",
   "	  ordf \\xaa laquo \\xab not \\xac shy \\xad reg \\xae",
   "	  hibar \\xaf deg \\xb0 plusmn \\xb1 sup2 \\xb2 sup3 \\xb3",
   "	  acute \\xb4 micro \\xb5 para \\xb6 middot \\xb7 cedil \\xb8",
   "	  sup1 \\xb9 ordm \\xba raquo \\xbb frac14 \\xbc frac12 \\xbd",
   "	  frac34 \\xbe iquest \\xbf Agrave \\xc0 Aacute \\xc1 Acirc \\xc2",
   "	  Atilde \\xc3 Auml \\xc4 Aring \\xc5 AElig \\xc6 Ccedil \\xc7",
   "	  Egrave \\xc8 Eacute \\xc9 Ecirc \\xca Euml \\xcb Igrave \\xcc",
   "	  Iacute \\xcd Icirc \\xce Iuml \\xcf ETH \\xd0 Ntilde \\xd1",
   "	  Ograve \\xd2 Oacute \\xd3 Ocirc \\xd4 Otilde \\xd5 Ouml \\xd6",
   "	  times \\xd7 Oslash \\xd8 Ugrave \\xd9 Uacute \\xda Ucirc \\xdb",
   "	  Uuml \\xdc Yacute \\xdd THORN \\xde szlig \\xdf agrave \\xe0",
   "	  aacute \\xe1 acirc \\xe2 atilde \\xe3 auml \\xe4 aring \\xe5",
   "	  aelig \\xe6 ccedil \\xe7 egrave \\xe8 eacute \\xe9 ecirc \\xea",
   "	  euml \\xeb igrave \\xec iacute \\xed icirc \\xee iuml \\xef",
   "	  eth \\xf0 ntilde \\xf1 ograve \\xf2 oacute \\xf3 ocirc \\xf4",
   "	  otilde \\xf5 ouml \\xf6 divide \\xf7 oslash \\xf8 ugrave \\xf9",
   "	  uacute \\xfa ucirc \\xfb uuml \\xfc yacute \\xfd thorn \\xfe",
   "	  yuml \\xff",
   "  }",
   "",
   "",
   "",
   "  array set tag_mapS {",
   "	  textarea    {fill 0}",
   "  }",
   "",
   "",
   "",
   "  proc tag_isindex {win param text} {",
   "	  upvar #0 HM$win var",
   "",
   "	  set item $win.$var(tags)",
   "	  if {[winfo exists $item]} {",
   "		  destroy $item",
   "	  }",
   "	  frame $item -relief ridge -bd 3",
   "	  set prompt \"Enter search keywords here\"",
   "	  extract_param $param prompt",
   "	  label $item.label -text [map_esc $prompt] -font $var(xfont)",
   "	  entry $item.entry",
   "	  bind $item.entry <Return> \"$item.submit invoke\"",
   "	  button $item.submit -text search -font $var(xfont) -command \\",
   "		  [format {submit_index %s {%s} [map_reply [%s get]]} \\",
   "		  $win $param $item.entry]",
   "	  pack $item.label -side top",
   "	  pack $item.entry $item.submit -side left",
   "",
   "",
   "	  $win insert $var(S_insert) \\n isindex",
   "	  win_install $win $item",
   "	  $win insert $var(S_insert) \\n isindex",
   "	  bind $item <Visibility> {focus %W.entry}",
   "  }",
   "",
   "",
   "  proc submit_index {win param text} {",
   "	  link_callback $win ?$text",
   "  }",
   "",
   "",
   "  proc tag_form {win param text} {",
   "	  upvar #0 HM$win var",
   "",
   "	  set id HM$win.form$var(tags)",
   "	  upvar #0 $id form",
   "",
   "	  if {[info exists var(form_id)]} {",
   "		  puts \"Missing end-form tag !!!! $var(form_id)\"",
   "		  tag_/form $win {} {}",
   "	  }",
   "	  catch {unset form}",
   "	  set var(form_id) $id",
   "",
   "	  set form(param) $param		;# form initial parameter list",
   "	  set form(reset) \"\"			;# command to reset the form",
   "	  set form(reset_button) \"\"	;# list of all reset buttons",
   "	  set form(submit) \"\"			;# command to submit the form",
   "	  set form(submit_button) \"\"	;# list of all submit buttons",
   "  }",
   "",
   "",
   "  proc tag_/form {win param text} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  foreach name [array names form radio_*] {",
   "		  regsub radio_ $name {} name",
   "		  lappend form(submit) [list $name \\$form(radio_$name)]",
   "	  }",
   "",
   "",
   "	  foreach item $form(reset_button) {",
   "		  $item configure -command $form(reset)",
   "	  }",
   "",
   "	  if {$form(submit_button) == \"\"} {",
   "		  input_submit $win {}",
   "	  }",
   "",
   "",
   "	  foreach item $form(submit_button) {",
   "		  set submit $form(submit)",
   "		  catch {lappend submit $form(submit_$item)}",
   "		  $item configure -command  \\",
   "				  [list submit_button $win $var(form_id) $form(param) \\",
   "				  $submit]",
   "	  }",
   "",
   "	  unset form(reset) form(submit) form(reset_button) form(submit_button)",
   "	  unset var(form_id)",
   "  }",
   "",
   "",
   "  proc tag_input {win param text} {",
   "	  upvar #0 HM$win var",
   "",
   "	  set type text	;# the default",
   "	  extract_param $param type",
   "	  set type [string tolower $type]",
   "	  if {[catch {input_$type $win $param} err]} {",
   "		  puts stderr $err",
   "	  }",
   "  }",
   "",
   "",
   "  proc input_text {win param {show {}}} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  extract_param $param name		;# required",
   "	  set item $win.input_text,$var(tags)",
   "	  set size 20; extract_param $param size",
   "	  set maxlength 0; extract_param $param maxlength",
   "	  entry $item -width $size -show $show",
   "",
   "	  set value \"\"; extract_param $param value",
   "	  $item insert 0 $value",
   "		  ",
   "	  win_install $win $item",
   "",
   "	  append form(reset) \";$item delete 0 end;$item insert 0 [list $value]\"",
   "	  lappend form(submit) [list $name \"\\[$item get]\"]",
   "",
   "	  if {$maxlength} {",
   "		  bindtags $item \"[bindtags $item] max$maxlength\"",
   "		  bind max$maxlength <KeyPress> \"%W delete $maxlength end\"",
   "	  }",
   "  }",
   "",
   "",
   "  proc input_password {win param} {",
   "	  input_text $win $param *",
   "  }",
   "",
   "",
   "  proc input_checkbox {win param} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  extract_param $param name",
   "	  extract_param $param value",
   "",
   "	  set variable $var(form_id)(check_$var(tags))	",
   "	  set item $win.input_checkbutton,$var(tags)",
   "	  checkbutton $item -variable $variable -offvalue {} -onvalue $value -text \"  \"",
   "	  if {[extract_param $param checked]} {",
   "		  $item select",
   "		  append form(reset) \";$item select\"",
   "	  } else {",
   "		  append form(reset) \";$item deselect\"",
   "	  }",
   "",
   "	  win_install $win $item",
   "	  lappend form(submit) [list $name \\$form(check_$var(tags))]",
   "  }",
   "",
   "",
   "  proc input_radio {win param} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  extract_param $param name",
   "	  extract_param $param value",
   "",
   "	  set first [expr {![info exists form(radio_$name)]}]",
   "	  set variable $var(form_id)(radio_$name)",
   "	  set variable $var(form_id)(radio_$name)",
   "	  set item $win.input_radiobutton,$var(tags)",
   "	  radiobutton $item -variable $variable -value $value -text \" \"",
   "",
   "	  win_install $win $item",
   "",
   "	  if {$first || [extract_param $param checked]} {",
   "		  $item select",
   "		  append form(reset) \";$item select\"",
   "	  } else {",
   "		  append form(reset) \";$item deselect\"",
   "	  }",
   "",
   "  }",
   "",
   "",
   "  proc input_hidden {win param} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "	  extract_param $param name",
   "	  extract_param $param value",
   "	  lappend form(submit) [list $name $value]",
   "  }",
   "",
   "",
   "  proc input_image {win param} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "	  extract_param $param name",
   "	  set name		;# barf if no name is specified",
   "	  set item [tag_img $win $param {}]",
   "	  $item configure -relief raised -bd 2 -bg blue",
   "",
   "",
   "	  set submit $win.dummy_submit,$var(tags)",
   "	  if {[winfo exists $submit]} {",
   "		  destroy $submit",
   "	  }",
   "	  button $submit	-takefocus 0;# this never gets mapped!",
   "	  lappend form(submit_button) $submit",
   "	  set form(submit_$submit) [list $name $name.\\$form(X).\\$form(Y)]",
   "	  ",
   "	  $item configure -takefocus 1",
   "	  bind $item <FocusIn> \"catch \\{$win see $item\\}\"",
   "	  bind $item <1> \"$item configure -relief sunken\"",
   "	  bind $item <Return> \"",
   "		  set $var(form_id)(X) 0",
   "		  set $var(form_id)(Y) 0",
   "		  $submit invoke	",
   "	  \"",
   "	  bind $item <ButtonRelease-1> \"",
   "		  set $var(form_id)(X) %x",
   "		  set $var(form_id)(Y) %y",
   "		  $item configure -relief raised",
   "		  $submit invoke	",
   "	  \"",
   "  }",
   "",
   "",
   "  proc input_reset {win param} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  set value reset",
   "	  extract_param $param value",
   "",
   "	  set item $win.input_reset,$var(tags)",
   "	  button $item -text [map_esc $value]",
   "	  win_install $win $item",
   "	  lappend form(reset_button) $item",
   "  }",
   "",
   "",
   "  proc input_submit {win param} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  extract_param $param name",
   "	  set value submit",
   "	  extract_param $param value",
   "	  set item $win.input_submit,$var(tags)",
   "	  button $item -text [map_esc $value] -fg blue",
   "	  win_install $win $item",
   "	  lappend form(submit_button) $item",
   "	  catch {set form(submit_$item) [list $name $value]}",
   "  }",
   "",
   "",
   "  proc tag_select {win param text} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "",
   "	  extract_param $param name",
   "	  set size 5;  extract_param $param size",
   "	  set form(select_size) $size",
   "	  set form(select_name) $name",
   "	  set form(select_values) \"\"		;# list of values to submit",
   "	  if {[extract_param $param multiple]} {",
   "		  set mode multiple",
   "	  } else {",
   "		  set mode single",
   "	  }",
   "	  set item $win.select,$var(tags)",
   "	  frame $item",
   "	  set form(select_frame) $item",
   "	  listbox $item.list -selectmode $mode -width 0 -exportselection 0",
   "	  win_install $win $item",
   "  }",
   "",
   "",
   "  proc tag_option {win param text} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "	  upvar $text data",
   "	  set frame $form(select_frame)",
   "",
   "	  if {[extract_param $param selected]} {",
   "	  lappend form(select_default) [$form(select_frame).list size]",
   "      }",
   "      set value [string trimright $data \" \\n\"]",
   "      $frame.list insert end $value",
   "	  extract_param $param value",
   "	  lappend form(select_values) $value",
   "	  set data \"\"",
   "  }",
   "   ",
   "",
   "  proc tag_/select {win param text} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "	  set frame $form(select_frame)",
   "	  set size $form(select_size)",
   "	  set items [$frame.list size]",
   "",
   "	  append form(reset) \";$frame.list selection clear 0  $items\"",
   "	  if {[info exists form(select_default)]} {",
   "		  foreach i $form(select_default) {",
   "			  $frame.list selection set $i",
   "			  append form(reset) \";$frame.list selection set $i\"",
   "		  }",
   "	  } else {",
   "		  $frame.list selection set 0",
   "		  append form(reset) \";$frame.list selection set 0\"",
   "	  }",
   "",
   "",
   "	  for {set i 0} {$i < $size} {incr i} {",
   "		  set value [format {[expr {[%s selection includes %s] ? {%s} : {}}]} \\",
   "				  $frame.list $i [lindex $form(select_values) $i]]",
   "		  lappend form(submit) [list $form(select_name) $value]",
   "	  }",
   "	  ",
   "",
   "	  if {$size > 1 && $items <= $size} {",
   "		  $frame.list configure -height $items",
   "		  pack $frame.list",
   "",
   "",
   "	  } elseif {$size > 1} {",
   "		  scrollbar $frame.scroll -command \"$frame.list yview\"  \\",
   "				  -orient v -takefocus 0",
   "		  $frame.list configure -height $size \\",
   "			  -yscrollcommand \"$frame.scroll set\"",
   "		  pack $frame.list $frame.scroll -side right -fill y",
   "",
   "",
   "	  } else {",
   "		  scrollbar $frame.scroll -command \"$frame.list yview\"  \\",
   "			  -orient h -takefocus 0",
   "		  $frame.list configure -height 1 \\",
   "			  -yscrollcommand \"$frame.scroll set\"",
   "		  pack $frame.list $frame.scroll -side top -fill x",
   "	  }",
   "",
   "",
   "	  foreach i [array names form select_*] {",
   "		  unset form($i)",
   "	  }",
   "  }",
   "",
   "",
   "  proc tag_textarea {win param text} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $var(form_id) form",
   "	  upvar $text data",
   "",
   "	  set rows 5; extract_param $param rows",
   "	  set cols 30; extract_param $param cols",
   "	  extract_param $param name",
   "	  set item $win.textarea,$var(tags)",
   "	  frame $item",
   "	  text $item.text -width $cols -height $rows -wrap none \\",
   "			  -yscrollcommand \"$item.scroll set\" -padx 3 -pady 3",
   "	  scrollbar $item.scroll -command \"$item.text yview\"  -orient v",
   "	  $item.text insert 1.0 $data",
   "	  win_install $win $item",
   "	  pack $item.text $item.scroll -side right -fill y",
   "	  lappend form(submit) [list $name \"\\[$item.text get 0.0 end]\"]",
   "	  append form(reset) \";$item.text delete 1.0 end; \\",
   "			  $item.text insert 1.0 [list $data]\"",
   "	  set data \"\"",
   "  }",
   "",
   "",
   "  proc tag_base {win param text} {",
   "	  variable urlS",
   "	  upvar #0 HM$win var",
   "	  extract_param $param href urlS",
   "  }",
   "",
   "",
   "  proc set_font {win tag font} {",
   "	  variable FontS",
   "	  if {![info exists FontS($font)]} {",
   "		  set FontS($font) 1",
   "		  ez_message msg \"Downloading font $font\"",
   "		  update",
   "	  }",
   "	  if {[catch {$win tag configure $tag -font $font} message]} {",
   "	  }",
   "  }",
   "",
   "",
   "  proc tag_color {win param text} {",
   "	  upvar #0 HM$win var",
   "	  set value bad_color",
   "	  extract_param $param value",
   "	  $win tag configure $value -foreground $value",
   "	  stack $win \"\" \"Tcolor $value\"",
   "  }",
   "",
   "  proc tag_/color {win param text} {",
   "	  upvar #0 HM$win var",
   "	  stack $win / \"Tcolor {}\"",
   "  }",
   "",
   "",
   "",
   "  proc tag_font {win param text} {",
   "	  upvar #0 HM$win var",
   "",
   "	  if {[extract_param $param size]} {",
   "	    stack $win \"\" \"size [expr {[lindex $var(size) end] + $size}]\"",
   "	  } else {",
   "	    stack $win \"\" [list size [lindex $var(size) end]]",
   "	  }",
   "	  set color bad_color",
   "	  extract_param $param color",
   "	  if {$color != \"\"} {",
   "	    $win tag configure $color -foreground $color",
   "	    stack $win \"\" \"Tcolor $color\"",
   "	  } else {",
   "	    stack $win \"\" \"Tcolor {}\"",
   "	  }",
   "  }",
   "",
   "  proc tag_/font {win param text} {",
   "	  upvar #0 HM$win var",
   "	  stack $win / \"size {}\"",
   "	  stack $win / \"Tcolor {}\"",
   "  }",
   "",
   "  proc tag_table {win param text} {",
   "	  upvar #0 HM$win var",
   "	  variable table_rowS",
   "	  variable table_alignS",
   "",
   "",
   "	  ez_message msg \"Generating table.  Please wait...\"",
   "",
   "	  array set align_map \\",
   "	    {top top    middle center    center center  bottom bottom}",
   "	  set align top",
   "	  extract_param $param align",
   "	  catch {set table_alignS $align_map([string tolower $align])}",
   "",
   "",
   "	  set border 0",
   "	  extract_param $param border",
   "",
   "	  set table_rowS 0",
   "",
   "	  set item $win.$var(tags)",
   "	  set label $item",
   "	  if {[extract_param $param width] && [extract_param $param height]} {",
   "	      frame $item -width $width -height $height -borderwidth $border -background blue",
   "	  } else {",
   "	      frame $item -height 550 -borderwidth $border ; # -background blue",
   "	  }",
   "	  if {[catch {set var(table_border_width) $border} emsg]} {",
   "	    puts stderr \"ERROR:$emsg\\n[stacktrace]\\n\"",
   "	  }",
   "",
   "	  set_state $win -curtable $item",
   "	  set_state $win -restore_win $win",
   "",
   "",
   "	  set tags [current_tags $win]",
   "	  foreach tag $tags {",
   "	       $win tag add $tag $item",
   "	  }",
   "	  return $item	;# used by the forms package for input_image types",
   "  }",
   "",
   "  proc tag_/table {win param text} {",
   "	  upvar #0 HM$win var",
   "	  variable table_rowS",
   "	  variable table_colS",
   "",
   "	  set w $var(curtable)",
   "",
   "	  if {[catch {$win window create $var(S_insert) -align top -window $w -pady 2 -padx 20} msg]} {",
   "	    puts stderr \"error:$msg\"",
   "	  }",
   "	  set_state $win -curtable {}",
   "",
   "	  if {[catch {$win see end-1l-1c} msg]} {",
   "	    puts stderr \"</TABLE>error:$msg\"",
   "	  }",
   "	  update",
   "	  for {set row 1} {$row <= $table_rowS} {incr row} {",
   "	    for {set col 1} {$col <= $table_colS} {incr col} {",
   "	      set holder $w.$row.$col",
   "	      set cell $holder.t",
   "	      if {[catch {set nwidth [calc_text_width $cell]} msg]} {",
   "		puts stderr \" </table>error\\[calc_text_width\\]:$msg\"",
   "		set nwidth 30",
   "	      }",
   "",
   "	      if {[catch {set nheight [calc_text_height $cell]} msg]} {",
   "		puts stderr \" </table>error\\[calc_text_height\\]:$msg\"",
   "		set nheight 30",
   "	      }",
   "",
   "	      set owidth [lindex [$holder configure -width] 4]",
   "	      set oheight [lindex [$holder configure -height] 4]",
   "	      $cell delete end-1c",
   "",
   "	      upvar #0 HM$cell cellvar",
   "	      if {[info exists cellvar(table_image)] && $cellvar(table_image)} {",
   "		 continue",
   "	      }",
   "	      if {[expr {$nwidth > $owidth}]} {",
   "		$holder configure -width $nwidth",
   "	      }",
   "	      if {[expr {$nheight > $oheight}]} {",
   "		$holder configure -height $nheight",
   "	      }",
   "	    }",
   "	  }",
   "",
   "	  for {set col 1} {$col <= $table_colS} {incr col} {",
   "	    set max_width 0",
   "	    for {set row 1} {$row <= $table_rowS} {incr row} {",
   "	      set holder $w.$row.$col",
   "	      set width [lindex [$holder configure -width] 4]",
   "	      if {[expr {$width > $max_width}]} {",
   "		set max_width $width",
   "	      }",
   "	    }",
   "	    for {set row 1} {$row <= $table_rowS} {incr row} {",
   "	      set holder $w.$row.$col",
   "	      $holder configure -width $max_width",
   "	    }",
   "	  }",
   "",
   "	  for {set row 1} {$row <= $table_rowS} {incr row} {",
   "	    set max_height 0",
   "	    for {set col 1} {$col <= $table_colS} {incr col} {",
   "	      set holder $w.$row.$col",
   "	      set height [lindex [$holder configure -height] 4]",
   "	      if {[expr {$height > $max_height}]} {",
   "		set max_height $height",
   "	      }",
   "	    }",
   "	    for {set col 1} {$col <= $table_colS} {incr col} {",
   "	      set holder $w.$row.$col",
   "	      $holder configure -height $max_height",
   "	    }",
   "	  }",
   "",
   "",
   "	  for {set row 1} {$row <= $table_rowS} {incr row} {",
   "	    for {set col 1} {$col <= $table_colS} {incr col} {",
   "	      set holder $w.$row.$col",
   "	      set cell $holder.t",
   "	      scan [$cell index end] %d num_lines",
   "	      $cell configure -width 0 ; # -height $num_lines",
   "	      pack propagate $holder 0",
   "	    }",
   "	  }",
   "	  update",
   "",
   "	  ez_message msg \"Done table...\"",
   "  }",
   "",
   "  proc tag_tr {win param text} {",
   "	  upvar #0 HM$win var",
   "	  variable table_rowS",
   "	  variable table_colS",
   "	  variable table_alignS",
   "",
   "	  incr table_rowS",
   "	  set table_colS 0",
   "",
   "	  set table_alignS {}",
   "",
   "	  array set align_map \\",
   "	    {left left    middle center    center center  right right}",
   "	  if {[extract_param $param align]} {",
   "	    catch {set table_alignS $align_map([string tolower $align])}",
   "	  }",
   "",
   "	  if {[catch {set w $var(curtable)} msg]} {",
   "	    puts stderr \"error:$msg\"",
   "	  }",
   "	  frame $w.$table_rowS -bd 0",
   "",
   "	  if {[extract_param $param color]} {",
   "	    set var(row_color) $color",
   "	  } else {",
   "	    set var(row_color) \"\"",
   "	  }",
   "  }",
   "",
   "  proc tag_/tr {win param text} {",
   "	  upvar #0 HM$win var",
   "	  variable table_rowS",
   "",
   "	  set w $var(curtable)",
   "	  pack $w.$table_rowS -side top -pady 0",
   "  }",
   "",
   "  proc tag_td {win param text} {",
   "      tag_cell td $win $param $text",
   "  }",
   "",
   "  proc tag_cell {tag win param text} {",
   "	  upvar #0 HM$win var",
   "	  variable table_rowS",
   "	  variable table_colS",
   "	  variable table_alignS",
   "",
   "	  incr table_colS",
   "",
   "",
   "	  set width 0",
   "	  set height 0",
   "	  if {[extract_param $param width]} {",
   "	    if {[string match \"*%\" $width]} {",
   "	      set width 0",
   "	    }",
   "	  }",
   "	  if {[extract_param $param height]} {",
   "	    if {[string match \"*%\" $height]} {",
   "	      set height 0",
   "	    }",
   "	  }",
   "",
   "	  set w $var(curtable)",
   "	  set holder $w.$table_rowS.$table_colS",
   "",
   "	  frame $holder -width $width -height $height -borderwidth 0",
   "	  pack $holder -side left -pady 0 -anchor n -fill both",
   "",
   "",
   "	  set item $holder.t",
   "	  text $item -borderwidth 0 -relief flat",
   "	  $item configure -highlightthickness $var(table_border_width)",
   "	  pack $item -side left -pady 0 -anchor n -expand 1 -fill both",
   "",
   "	  if {[extract_param $param bgcolor]} {",
   "	    $item configure -background $bgcolor",
   "	  } elseif {$var(row_color) != \"\"} {",
   "	    $item configure -background $var(row_color)",
   "	  }",
   "",
   "	  array set align_map \\",
   "	      {left left    middle center   center center   right right}",
   "	  if {[extract_param $param align]} {",
   "	    catch {set cell_align $align_map([string tolower $align])}",
   "	  } else {",
   "	    if {$table_alignS != \"\"} {",
   "	      set cell_align $table_alignS",
   "	    } else {",
   "	      if {$tag == \"td\"} {",
   "	        set cell_align left",
   "	      } else {",
   "	        set cell_align center",
   "	      }",
   "	    }",
   "	  }",
   "",
   "	  $item delete 1.0 end",
   "	  $item insert end $text",
   "",
   "	  catch {$item tag delete ic_justify} msg",
   "	  $item tag add ic_justify 1.0 end",
   "	  $item tag configure ic_justify -justify $cell_align",
   "",
   "",
   "	  set_state $win -divert_win $item",
   "	  set_state $win -divert 1",
   "",
   "	  set win_new $var(divert_win)",
   "	  init_win $win_new",
   "	  upvar #0 HM$win_new new_var",
   "	  array set new_var [array get var *]",
   "	  set new_var(table_image) 0",
   "",
   "	  set tags [current_tags $win]",
   "	  foreach tag $tags {",
   "	    $win tag add $tag $item",
   "	  }",
   "    }",
   "",
   "",
   "    proc tag_/td {win param text} {",
   "	  upvar #0 HM$win var",
   "	  variable table_rowS",
   "	  variable table_colS",
   "",
   "	  set wincell $var(divert_win)",
   "	  set_state $win -divert_win {}",
   "	  set_state $win -divert 0",
   "	  $wincell insert end \\n",
   "	  scan [$wincell index end] %d num_lines",
   "	  $wincell configure -height [expr {$num_lines + 2}]",
   "  }",
   "",
   "  proc tag_th {win param text} {",
   "      tag_cell th $win $param $text",
   "  }",
   "",
   "  proc tag_/th {win param text} {",
   "    tag_/td $win $param $text",
   "  }",
   "",
   "",
   "  proc tag_script {win param text} {",
   "	variable configS",
   "    if {[extract_param $param src]} {",
   "	  if {($src == \"utdinclude.js\")} {",
   "	    set text \"load(\\\"$::twez::configS(E_rootdir)/tcl/EZ/javascript/$src\\\")\"",
   "	  } else {",
   "	    variable urlS",
   "	    set dirname [file dirname $urlS]",
   "	    set full_src [file join $dirname $src]",
   "	    set text \"load(\\\"$full_src\\\")\"",
   "	  }",
   "    }",
   "    twjavascript $text $win",
   "  }",
   "",
   "",
   "  proc tag_/script {win param text} {",
   "      set_state $win -ignore 0",
   "  }",
   "",
   "",
   "",
   "",
   "  proc win_install {win item} {",
   "	  upvar #0 HM$win var",
   "	  $win window create $var(S_insert) -window $item -align bottom",
   "	  $win tag add indent$var(level) $item",
   "	  set focus [expr {[winfo class $item] != \"Frame\"}]",
   "	  $item configure -takefocus $focus",
   "	  bind $item <FocusIn> \"$win see $item\"",
   "  }",
   "",
   "",
   "  proc submit_button {win form_id param stuff} {",
   "	  upvar #0 HM$win var",
   "	  upvar #0 $form_id form",
   "	  set query \"\"",
   "	  foreach pair $stuff {",
   "		  set value [subst [lindex $pair 1]]",
   "		  if {$value != \"\"} {",
   "			  set item [lindex $pair 0]",
   "			  lappend query $item $value",
   "		  }",
   "	  }",
   "	  submit_form $win $param $query",
   "  }",
   "",
   "",
   "  proc submit_form {win param query} {",
   "	  set result \"\"",
   "	  set sep \"\"",
   "	  foreach i $query {",
   "	    append result  $sep [map_reply $i]",
   "	    if {$sep != \"=\"} {",
   "	      set sep =",
   "	    } else {",
   "	      set sep &",
   "	    }",
   "	  }",
   "	  puts $result",
   "  }",
   "",
   "   ",
   "  for {set i 1} {$i <= 256} {incr i} {",
   "      set c [format %c $i]",
   "      if {![string match \\[$alphanumericS\\] $c]} {",
   "	  set form_mapS($c) %[format %.2x $i]",
   "      }",
   "  }",
   "",
   "  array set form_mapS {",
   "      \" \" +   \\n %0d%0a",
   "  }",
   "",
   "   ",
   "   ",
   "  proc map_reply {string} {",
   "      variable form_mapS",
   "      variable alphanumericS",
   "      regsub -all \\[^$alphanumericS\\] $string {$form_mapS(&)} string",
   "      regsub -all \\n $string {\\\\n} string",
   "      regsub -all \\t $string {\\\\t} string",
   "      regsub -all {[][{})\\\\]\\)} $string {\\\\&} string",
   "      return [subst $string]",
   "  }",
   "",
   "",
   "",
   "  proc cgiDecode {data} {",
   "	  set data [split $data \"&=\"]",
   "	  foreach i $data {",
   "		  lappend result [cgiMap $i]",
   "	  }",
   "	  return $result",
   "  }",
   "",
   "  proc cgiMap {data} {",
   "	  regsub -all {\\+} $data \" \" data",
   "	  ",
   "	  if {[regexp % $data]} {",
   "		  regsub -all {([][$\\\\])} $data {\\\\\\1} data",
   "		  regsub -all {%([0-9a-fA-F][0-9a-fA-F])} $data  {[format %c 0x\\1]} data",
   "		  return [subst $data]",
   "	  } else {",
   "		  return $data",
   "	  }",
   "  }",
   "",
   "} ; # end namespace twez",
  NULL };

 /* Find out how long the script is */
 length = 0;
 for (i=0;i<size;i++) length += strlen(cmds[i]);
 /* Catenate the script */
 script = UTDCALLOC(length+size+1,char);
 script[0] = '\0';
 for (i=0;i<size;i++) 
 {
  strcat(script,cmds[i]);
  strcat(script,"\n");
 }
 /* Execute the script */
 err = Tcl_Eval(interp,script);
 UTDFREE(script);
 if (err != TCL_OK)
 {
  utDmsgf(ERRMSG,MSG_AT, "EZengine", "html_library.tcl : %s\n",Tcl_GetStringResult(interp)) ;
  trace = Tcl_GetVar(interp,"errorInfo",TCL_GLOBAL_ONLY);
  if (trace ){
   utDmsgf(ERRMSG, MSG_AT, "EZengine","*** TCL TRACE ***\n");
   utDmsgf(ERRMSG, MSG_AT, NULL, "%s\n",trace);
   return TCL_ERROR;
  }
 }
 return TCL_OK;
}

