#!/bin/sh
# This comment makes this script an executable. Do *NOT* delete \
eval exec ${ICDIR}/bin/icos itranslate -v -do $0 ${1+"$@"}

set routine place
set previous floorplan

global env
global argv
global icdirG
if {[info exists env(ICDIR)]} {
  set icdirG $env(ICDIR)
} {
  puts stderr "ERROR:cannot get iTools environment variable:ICDIR"
  exit 1
}
lappend auto_path $icdirG/tcl/common

set args $argv
set num_args [llength $args]
for {set i 0} {$i < $num_args} {incr i} {
  set arg_el [lindex $args $i]
  twmessage imsg null "argv\[$i]: $arg_el\n"
}
incr i -1
set dsn [lindex $args $i]

twbackup_directory place
cd place

# Now source any necessary do files.
::utdtools::source_flow_do_files $dsn p

set num_parts $::utdtools::numPartitionS
set dsn $::utdtools::designNameS
twmessage imsg null "Welcome to the TimberWolf SimPlace Program...\n"
twmessage imsg null "We are going to process $num_parts...\n"

# Now do some functionality
# We should be in the floorplan directory as we created a directory here.
# eval exec ${OPENROAD}/bin/Darwin/flow -s p -dir cut .... 
set dirname [pwd]
set folder [file tail $dirname]
if {$folder != "place"} {
  twmessage errmg $routine "we are not in the proper directory:$folder\n"
  twwait
  exit 1
}

# ######################## LEF ############################
set input_name $::utdtools::lef_fileS
if {$input_name != ""} {
  # change this to multiple files if needed
  set fpath [::utdtools::search_input $input_name [list . ../${previous}/output ../ ../../] true]
  if {$fpath == ""} {
    twmessage errmsg $routine "No input file named $input_name found. Aborting\n"
    twwait
    exit 1
  }
}
twmessage imsg $routine "reading LEF file:$fpath\n"
twread_lef $fpath -scale -model_obs keepout

# We need to do this for TimberWolf
if {([info exists ::utdtools::feednameS]) && ($::utdtools::feednameS != "")} {
  twmake_default_feedthru -exists $::utdtools::feednameS
}

# ######################## TIMING ############################
set input_name $::utdtools::timing_fileS
if {$input_name != ""} {
  # change this to multiple files if needed
  set fpath [::utdtools::search_input $input_name [list . ../${previous}/output ../ ../../] true]
  if {$fpath == ""} {
    twmessage errmsg $routine "No input file named $input_name found. Aborting\n"
    twwait
    exit 1
  }
}
twmessage imsg $routine "reading Synopsys Library file:$fpath\n"
twread_synopsys -new $fpath

# ######################## DEF ############################
set input_name $::utdtools::def_fileS
if {$input_name != ""} {
  # change this to multiple files if needed
  set fpath [::utdtools::search_input $input_name [list . ../${previous}/output ../ ../../] true]
  if {$fpath == ""} {
    twmessage errmsg $routine "No input file named $input_name found. Aborting\n"
    twwait
    exit 1
  }
}
twmessage imsg $routine "reading DEF file:$fpath\n"
twread_def $fpath -convert_to_exact_pads


# Now output the TimberWolf files
twbackup_directory timberwolf
twbackup_directory output
cd timberwolf
# Don't want to confuse things use TimberWolf default script.
twpar_option ICSC autodetect_script off
twpar_option ICSC fast 10
twwrite_ic -notplaced -writerows
twbackup_directory floorplan/output
file copy ${dsn}.con [file join floorplan output itools.con]

set icos [file join $icdirG bin icos]

###################################################################
# Now call the syntax check and the placer.
###################################################################
if {([info exists ::utdtools::nographicsS]) && ($::utdtools::nographicS)} {
  append opts " -n -v"
} else {
  append opts " -v"
}
if {[catch {eval bgexec statusG -output outputG $icos icdir $icdirG syntax -v ${dsn}} msg]} {
  set fp [open "problem" w]
  puts $fp "we got the following msg:$msg"
  close $fp
}
if {[catch {eval bgexec statusG -output outputG $icos icdir $icdirG iplacesc ${opts} ${dsn}} msg]} {
  set fp [open "problem" w]
  puts $fp "we got the following msg:$msg"
  close $fp
}

# Create the ${dsn}_final.tdo script.
set f [open ${dsn}_final.tdo w]
puts $f "twread_itools::state place"
puts $f "twwrite_def \[file join ../ output ${dsn}.def] -placed \
-sections {rows nocoresites vias components pins nets}"
puts $f "exit"
close $f

# Next call translator to create output files.
if {[catch {bgexec statusTG -output outputG $icos icdir $icdirG itranslate -v -do ${dsn}_final.tdo ${dsn}} msg]} {  
  set fp [open "problem" w]
  puts $fp "we got the following msg:$msg"
  close $fp
}

twmessage imsg twplace "placement completed.\n"
exit 0
